name: Backend CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download build artifact
      uses: dawidd6/action-download-artifact@v2
      with: 
        name: backend-release-master
        workflow: dotnet.yml # Change it to backend-CI.yml once finalized; can't rename it now, because it wouldn't be testable from non-default branch.
    - name: Publish
      run: dotnet publish --no-build -c Release -o my-release
    - name: 'Deploy to Azure'
      uses: azure/webapps-deploy@v2
      with:
        app-name: mywarehouseapi
        publish-profile: ${{ secrets.AZURE_PUBLISHING_PROFILE }}
        package: './my-release'
