name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      #Test if we can run localdb integration tests on Windows vm
      #run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName!~MyWarehouse.Application.IntegrationTests
      env:
          UserSeedSettings__SeedDefaultUser: false
          AuthenticationSettings__JwtSigningKeyBase64: e09053f6847d466b8f243d9522c340ef234sdfds # Not actually used.
          SwaggerSettings__UseSwagger: false
