
# This workflow runs the unit tests and integration tests for the backend.
# Integration tests use real SQL database, but fortunately windows-latest
# image contains support for SQL Express localDb.
# This approach is significantly simpler than running it via docker-compose,
# although, yes, it's more prone to breaking, since it's not isolated.

name: .NET Core

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal
      env:
        UserSeedSettings__SeedDefaultUser: false
        AuthenticationSettings__JwtSigningKeyBase64: e09053f6847d466b8f243d9522c340ef234sdfds # Not actually used.
        SwaggerSettings__UseSwagger: false
    - uses: actions/upload-artifact@v2
      with:
        name: backend-release-${GITHUB_REF##*/} # Suffixed with branch name
        path: src/WebApi